apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest-service
  name: rest-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-service
  strategy: {}
  template:
    metadata:
      labels:
        app: rest-service
    spec:
      containers:
      - image: myorg/myapp
        name: myapp
        resources: {}
        imagePullPolicy: Never
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rest-service
  name: rest-service
spec:
  ports:
  - name: http
    nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rest-service
  type: NodePort
status:
  loadBalancer: {}
